//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.34014
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>T
//------------------------------------------------------------------------------
using System;
using System.Timers;


namespace AssemblyCSharp
{
		public class GameTime
		{


				private static GameTime _instane;

				public static  GameTime Instance {
						get {
								if (_instane == null) {
										_instane = new GameTime ();

								}
				return _instane;
						}
						
				}
		public Timer GetTimer(double intarve,ElapsedEventHandler eventhndle){
			var timer = new Timer (intarve);
			timer.Elapsed += eventhndle;
			timer.Start ();
			return timer;
		
		}

				public GameTime ()
				{

				}
		}
}

